# Generated by Django 3.2.9 on 2022-01-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='hello', max_length=50, verbose_name='comment'),
            preserve_default=False,
        ),
    ]
