# Generated by Django 3.2.9 on 2022-01-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220107_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_attribution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
