# Generated by Django 3.2.9 on 2022-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_image_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_attribution_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
